spring:
  profiles:
    active: local

spring.batch.job.names: ${job.name:NONE}
logging.level.org.springframework.batch: DEBUG
---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
      driver-class-name: org.h2.Driver
  config:
    activate:
      on-profile: local
---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:mysql://chae-work.ddns.net:3306/mysql
      username: bubsakk
      password: tlsfkaus13!#
      driver-class-name: com.mysql.cj.jdbc.Driver
  config:
    activate:
      on-profile: mysql
---
spring:
  datasource:
    hikari:
      jdbc-url: jdbc:oracle:thin:@chae-work.ddns.net:1521/ORCLPDB1
      username: webUser
      password: webUserPw
      driver-class-name: oracle.jdbc.driver.OracleDriver
  config:
    activate:
      on-profile: oracle